buscoayuda4101/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'buscoayuda4101.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('polls.urls', namespace="principal")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^editar/(?P<idTrabajador>\d+)$', views.editar_perfil, name='editar'),
    url(r'^login$', views.login),
    url(r'^register', views.register),
    url(r'^logout$', views.logout),
    url(r'^trabajador/(?P<pk>\d+)$', views.detail),
    url(r'^detail', views.detalle_trabajador),
    url(r'^addComment', views.add_comment),
    url(r'^mostrarComentarios/(?P<idTrabajador>\d+)$', views.mostrarComentarios),
    url(r'^mostrarTrabajadores/(?P<tipo>\w+)$', views.mostrarTrabajadores),
    url(r'^mostrarTrabajadores', views.mostrarTrabajadores),
    url(r'^tipoServicio/(?P<pk>\d+)$', views.getTiposDeServicio),
]

polls/models.py
# coding=utf-8
from __future__ import unicode_literals

from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm


class TiposDeServicio(models.Model):
    nombre = models.CharField(max_length=1000)
    imagen = models.ImageField(upload_to='services')

    def __unicode__(self):
        return u'{0}'.format(self.nombre)


class Trabajador(models.Model):
    nombre = models.CharField(max_length=1000)
    apellidos = models.CharField(max_length=1000)
    aniosExperiencia = models.IntegerField()
    tiposDeServicio = models.ForeignKey(TiposDeServicio, null=True)
    telefono = models.CharField(max_length=1000)
    correo = models.CharField(max_length=1000)
    imagen = models.ImageField(upload_to='photos')
    usuarioId = models.OneToOneField(User, null=True)


class Comentario(models.Model):
    texto = models.CharField(max_length=1000)
    trabajador = models.ForeignKey(Trabajador, null=True)
    correo = models.CharField(max_length=1000)


class TrabajadorForm(ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese sus nombres'})
    )
    apellidos = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese sus apellidos'})
    )
    aniosExperiencia = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad de años de experiencia'}),
        label='Años De Experiencia'
    )
    tiposDeServicio = forms.ModelChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        queryset=TiposDeServicio.objects.all(),
        empty_label='Seleccione el tipo de servicio que ofrecerá',
        label='Tipo De Servicio'
    )
    telefono = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Número telefónico'}),
        label='Teléfono'
    )
    correo = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        label='Correo'
    )

    class Meta:
        model = Trabajador
        fields = ['nombre', 'apellidos', 'aniosExperiencia', 'tiposDeServicio', 'telefono', 'correo', 'imagen']


class UserForm(ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Usuario'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Contraseña'
    )

    class Meta:
        model = User
        fields = ['username', 'password']

polls/views.py
# coding=utf-8
import datetime

import boto
from django.conf import settings
from django.contrib.auth.models import User
from django.core import serializers
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Trabajador, TrabajadorForm, UserForm, Comentario
from .models import TiposDeServicio
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib import auth


def index(request):
    trabajadores = Trabajador.objects.all()
    tipos_de_servicios = TiposDeServicio.objects.all()
    form_trabajador = TrabajadorForm(request.POST)
    form_usuario = UserForm(request.POST)

    context = {'trabajadores': trabajadores, 'tipos_de_servicios': tipos_de_servicios,
               'form_trabajador': form_trabajador, 'form_usuario': form_usuario, 'base_url': settings.STATIC_URL}
    return render(request, 'polls/index.html', context)


def login(request):
    username = request.POST.get('usrname', '')
    password = request.POST.get('psw', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        messages.success(request, "Bienvenido al sistema {}".format(username), extra_tags="alert-success")
        return HttpResponseRedirect('/')
    else:
        messages.error(request, "¡El usuario o la contraseña son incorrectos!", extra_tags="alert-danger")
        return HttpResponseRedirect('/')


def logout(request):
    auth.logout(request)
    messages.info(request, "Cerraste sesión exitosamente", extra_tags="alert-info")
    return HttpResponseRedirect('/')


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.create_user(username=username, password=password)
        user.first_name = request.POST.get('nombre')
        user.last_name = request.POST.get('apellidos')
        user.email = request.POST.get('correo')
        user.save()



        nuevo_trabajador=Trabajador(nombre=request.POST['nombre'],
                                      apellidos=request.POST['apellidos'],
                                      aniosExperiencia=request.POST.get('aniosExperiencia'),
                                      tiposDeServicio=TiposDeServicio.objects.get(pk=request.POST.get('tiposDeServicio')),
                                      telefono=request.POST.get('telefono'),
                                      correo=request.POST.get('correo'),
                                      #imagen=request.FILES['imagen'],
                                      usuarioId=user)
        nuevo_trabajador.save()

    return HttpResponseRedirect('/')

def editar_perfil(request,idTrabajador):
    trabajador=Trabajador.objects.get(usuarioId=idTrabajador)
    if request.method == 'POST':
        # formulario enviado
        form_trabajador = TrabajadorForm(request.POST, request.FILES, instance=trabajador)

        if form_trabajador.is_valid():
            # formulario validado correctamente
            form_trabajador.save()
            return HttpResponseRedirect('/')

    else:
        # formulario inicial
        form_trabajador = TrabajadorForm(instance=trabajador)

    context = {'form_trabajador': form_trabajador}
    return render(request, 'polls/editar.html', context)

@csrf_exempt
def add_comment(request):
    if request.method == 'POST':
       new_comment = Comentario(texto=request.POST.get('texto'),
                                      trabajador=Trabajador.objects.get(pk=request.POST.get('trabajador')),
                                      correo=request.POST.get('correo'))
       new_comment.save()
    return HttpResponse(serializers.serialize("json", [new_comment]))

@csrf_exempt
def mostrarTrabajadores(request, tipo=""):
    if tipo == "":
      lista_trabajadores = Trabajador.objects.all()
    else:
      lista_trabajadores = Trabajador.objects.select_related().filter(tiposDeServicio__nombre__icontains=tipo)


    return HttpResponse(serializers.serialize("json", lista_trabajadores))

@csrf_exempt
def mostrarComentarios(request, idTrabajador):
    lista_comentarios =Comentario.objects.filter(trabajador=Trabajador.objects.get(pk=idTrabajador))

    return HttpResponse(serializers.serialize("json", lista_comentarios))

def getTiposDeServicio(request, pk):
    tipo = TiposDeServicio.objects.get(pk=pk)
    return HttpResponse(serializers.serialize("json", [tipo]))

def detalle_trabajador(request):
    return render(request, "polls/detalle.html")


def detail(request, pk):
    trabajador = get_object_or_404(Trabajador, pk=pk)
    return HttpResponse(serializers.serialize("json", [trabajador]))

polls/templates/polls/detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalle Independiente</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
    <script src="/designMatch/recursos/jquery.bootpag.min.js"></script>
    <script>
        var trabajador = localStorage.getItem('trabajador');

        (function () {
            $.getJSON("/trabajador/" + trabajador).done(function (data) {
                $.each(data, function (key, val) {
                    $('#nombres').prepend('<h2>' + val.fields.nombre + ' ' + val.fields.apellidos + '</h2>');
                    $('#foto').prepend('<a><img src="https://miso4202.s3.amazonaws.com/' + val.fields.imagen + '" class="media-object" style="width: 250px; height: 300px"></a>');
                    $('#detalle').prepend('<br><br><br>' +
                            '<h4><b>Experiencia: </b>' + val.fields.aniosExperiencia + ' años</h4><br>' +
                            '<h4><b>Telefono: </b>' + val.fields.telefono + '</h4><br>' +
                            '<h4><b>Correo electrónico: </b>' + val.fields.correo + '</h4>');
                })
            });
        })();

        mostrarComentarios();
        function mostrarComentarios(){
            $.getJSON("/mostrarComentarios/" + trabajador).done(function (data) {
                $.each(data, function (key, val) {

                    var div='<div style="box-shadow: 2px 2px 5px gray; border-radius: 5px" class="col-md-6 col-md-offset-3">'+
                                  '<h4>'+val.fields.correo+'</h4>'+
                                  '<p>'+val.fields.texto+'</p></div>';
                  $('#comentarios').append(div);
                })
            });
        }


        function agregarComentario(){
            $.post( "/addComment", { texto: $('#comentario').val(), trabajador: trabajador, correo: $('#correo').val() })
              .done(function( data ) {
                  mostrarComentarios();
              });
        }
    </script>
</head>
<body>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div id="nombres" align="center" class="page-header">
        </div>
        <div class="media">
            <div id="foto" class="media-left media-middle">
            </div>
            <div id="detalle" style="padding-left: 1em" class="media-body">
            </div>
        </div>
        <div align="center" class="page-header">
            <h2>Comentarios</h2>
        </div>
        <div align="right">
            <a href="/" class="btn btn-default btn-default"><span
                    class="glyphicon glyphicon-step-backward">Volver</span></a>
        </div>
    </div>
</div>
<div class="row">
    <div style="box-shadow: 2px 2px 5px gray; border-radius: 5px" class="col-md-6 col-md-offset-3">
        <form onsubmit="agregarComentario()">
         <input id="correo" style="margin: 5px;" type="email" required placeholder="Correo">
         <textarea placeholder="Agreagar comentario" id="comentario" style="margin: 5px;" rows="3" cols="90" required></textarea>

        <button type="submit" style="margin: 5px;" class="btn btn-default btn-success" title="Adicionar comentario">Comentar <span class="glyphicon glyphicon-plus"></span>
        </button>
        </form>

     </div>
    </div>
    <div id="comentarios" class="row">
</div>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Busco Ayuda</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style type="text/css">
        .float-message {
            position: fixed;
            top: 1%;
            width: 100%;
            z-index: 9999;
        }
        /*noinspection CssUnusedSymbol*/
        .form-group label.error {
            color: #FB3A3A;
            display: inline-block;
            text-align: right;
            width: 100%;
        }


    </style>
</head>
<body>
<ul class="nav navbar-nav navbar-right" style="padding-right: 20px">
    {% if user.is_authenticated %}

            <li><a href="{% url 'principal:editar' idTrabajador=user.id %}" id="id_editar"><span class="glyphicon glyphicon-user"></span> Editar</a></li>
    <li>
            <a href="logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
        </li>
    {% else %}
        <li><a href="#" id="id_register"><span class="glyphicon glyphicon-user"></span> Registrarse</a></li>
        <li><a href="#" id="id_login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    {% endif %}
</ul>
<div class="jumbotron" style="padding-left: 20px; height: 50%">
    <h1>Busco Ayuda</h1>
    <p>Encuentra aquí la ayuda que necesitas.</p>
</div>
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} float-message">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}<strong>ERROR: </strong> {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}<strong>SUCCESS: </strong> {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}<strong>INFO: </strong> {% endif %}
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% if not user.is_authenticated %}
    <form class="navbar-form navbar-right" role="search">
        <div class="input-group">
            <input  type="text" class="form-control" placeholder="Buscar" name="srch-term" id="buscar">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </form>
    <div class="col-lg-12">
    </div>
    <div id="trabajadores">
    {% for trabajador in trabajadores %}
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading" style="text-align: center; background-color: black;">
                    <span style="color: white; font-size: large;">{{ trabajador.tiposDeServicio.nombre }}</span>
                    <!--suppress HtmlUnknownTarget -->
                    <img src="https://miso4202.s3.amazonaws.com/{{ trabajador.tiposDeServicio.imagen }}" />
                </div>
                <div class="panel-body" style="text-align: center">
                    <a class="trabajador" href="#" data-form="{{ trabajador.id }}" style="text-decoration: none;">
                        <!--suppress HtmlUnknownTarget -->
                        <img class="thumbnail img-responsive center-block"
                             src="https://miso4202.s3.amazonaws.com/{{ trabajador.imagen }}" width="300"
                             height="300">
                        <span>{{ trabajador.nombre }} {{ trabajador.apellidos }}</span>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% else %}
    <div class="container" style="padding: 5px">
        {% if user.is_authenticated and user.is_superuser %}
            <h3>Administrar</h3>
            <p>Salir del sitio e ir al módulo de administración principal del sistema en Django.</p>
            <a class="glyphicon glyphicon-exclamation-sign" href="admin" target="_blank"> Abrir</a>
        {% endif %}
    </div>
{% endif %}
{% include "polls/registro.html" %}
<!--suppress JSUnresolvedFunction -->
<script>
    $(document).ready(function () {
        $('#id_login').click(function () {
            $('#login_modal').modal();
        });
        $('#id_register').click(function () {
            $('#register_modal').modal();
        });

        $('.trabajador').click(function () {
            var trabajador = $(this).data("form");
            localStorage.setItem('trabajador', trabajador);
            window.location = "/detail";
        });
        $('.float-message').fadeTo(2000, 500).slideUp(500, function(){
            $('#success-alert').alert('close');
        });

        $("#buscar").keyup(function(){
            $('#trabajadores').clear;
            mostrarTrabajadores();
});
    });
    function detalle(id){
            localStorage.setItem('trabajador', id);
            window.location = "/detail";
}

    function mostrarTrabajadores(){

        $.getJSON("/mostrarTrabajadores/" + $("#buscar").val()).done(function (data) {
            $('#trabajadores').empty();
                $.each(data, function (key, val) {
                    $.get( "/tipoServicio/"+val.fields.tiposDeServicio, function( dataTipo ) {
                        dataTipo=jQuery.parseJSON(dataTipo);
                      var tipo=dataTipo[0].fields.nombre;
                      var imagenTipo= dataTipo[0].fields.imagen;

                    var div='<div class="col-sm-4 col-md-3">'+
                            '<div class="panel panel-default">'+
                                '<div class="panel-heading" style="text-align: center; background-color: black;">'+
                                    '<span style="color: white; font-size: large;">'+tipo+'</span>'+
                                    '<img src="https://miso4202.s3.amazonaws.com/'+imagenTipo+'" />'+
                                '</div>'+
                                '<div class="panel-body" style="text-align: center">'+
                                    '<a onclick="detalle('+val.pk+')" class="trabajador" href="#" data-form="'+val.fields.id+'" style="text-decoration: none;">'+
                                        '<img class="thumbnail img-responsive center-block"'+
                                             'src="https://miso4202.s3.amazonaws.com/'+val.fields.imagen+'" width="300"'+
                                             'height="300">'+
                                        '<span>'+val.fields.nombre+' '+val.fields.apellidos+'</span>'+
                                    '</a>'+
                                '</div>'+
                            '</div>'+
                        '</div>';
                        $('#trabajadores').append(div);
                    });
                })
            });
    }
</script>
</body>
</html>

polls/templates/polls/registro.html
<div class="modal fade" id="register_modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4><span class="glyphicon glyphicon-user"></span> Registrarse</h4>
            </div>
            <!--suppress HtmlUnknownTarget -->
            <form role="form" action="register" method="post" enctype="multipart/form-data" id="register-form" novalidate="novalidate">
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in form_trabajador %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    {% for field in form_usuario %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer btn-toolbar">
                    <button type="submit"id="id_grabar" class="btn btn-default btn-success pull-right">
                        <span class="glyphicon glyphicon-save"></span> Guardar
                    </button>
                    <button type="submit" class="btn btn-default btn-default pull-right" data-dismiss="modal"
                            style="margin-left: 5px">
                        <span class="glyphicon glyphicon-remove"></span> Cancelar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--suppress JSUnresolvedFunction -->
<script type="text/javascript">
    $(document).ready(function () {
        var validator = $("#register-form").validate({
            rules: {
                nombre: "required",
                apellidos: "required",
                aniosExperiencia: {
                    min: 0,
                    required: true,
                    number: true
                },
                tiposDeServicio: {
                    required: true,
                    min: 1
                },
                telefono: {
                    required: true,
                    minlength: 5
                },
                correo: {
                    required: true,
                    email: true
                },
                username: "required",
                password: {
                    required: true,
                    minlength: 8
                }
            },
            messages: {
                nombre: "Por favor ingrese su nombre completo",
                apellidos: "Por favor ingrese sus apellidos",
                aniosExperiencia: "Por favor indique cuantos a&ntilde;os de experiencia tiene",
                tiposDeServicio: "Por favor seleccione el tipo de servicio que ofrecer&aacute;",
                telefono: "Por favor ingrese un tel&eacute;fono v&aacute;alido",
                correo: "Por favor ingrese un correo v&aacute;lido",
                imagen: "Por favor suba una foto",
                username: "Por favor ingrese su usuario",
                password: "Por favor ingrese su contrase&ntilde;a",
                confirmar: {
                    equalTo: "La confirmaci&oacute;n no es v&aacute;lida"
                }
            },
            submitHandler: function (form) {
                form.submit();
            }
        });
        $('#imagen').click(function () {
            alert($('input[type=file]').val());
            return true;

        });
        $('#register_modal').on('hidden.bs.modal', function () {
            validator.resetForm();
        })
    });
</script>